// Generated by CoffeeScript 1.10.0
var Animated, type;

Animated = require("./Animated");

type = Type("AnimatedWithChildren");

type.inherits(Animated);

type.defineFrozenValues({
  _children: function() {
    return [];
  }
});

type.defineMethods({
  __getChildren: function() {
    return this._children;
  },
  __addChild: function(child) {
    if (this._children.length === 0) {
      this.__attach();
    }
    return this._children.push(child);
  },
  __removeChild: function(child) {
    var index;
    index = this._children.indexOf(child);
    if (index < 0) {
      return;
    }
    this._children.splice(index, 1);
    if (this._children.length === 0) {
      return this.__detach();
    }
  }
});

module.exports = type.build();
