// Generated by CoffeeScript 1.11.1
var LazyMap;

require("LazyVar");

LazyMap = require("LazyMap");

module.exports = LazyMap({
  Animation: function() {
    return require("./Animation");
  },
  AnimatedValue: function() {
    return require("./nodes/AnimatedValue");
  },
  AnimatedProps: function() {
    return require("./nodes/AnimatedProps");
  },
  AnimatedStyle: function() {
    return require("./nodes/AnimatedStyle");
  },
  AnimatedTransform: function() {
    return require("./nodes/AnimatedTransform");
  },
  AnimatedWithChildren: function() {
    return require("./nodes/AnimatedWithChildren");
  },
  Animated: function() {
    return require("./nodes/Animated");
  },
  NativeAnimated: function() {
    return require("./NativeAnimated");
  }
});
